### ISSUE TITLE
Distance between badgers

### ISSUE THREAD

**Issue by roughprada** [redbadger/badger-map#12]
It will be great to have the distance between badger by foot or bike, so if someone needs help or someone want to help each other, they can see how far they are.

Eg. I'll go to buy groceries and there is a lot of toilet paper. I can see that I am a short ride from Reece, so I can bring him some :)

**Comment by charypar** [comment]
This API looks useful: https://developers.google.com/maps/documentation/distance-matrix/intro

**Comment by charypar** [comment]
Finished in #20.
